@startuml
ditaa

                   hBPF CPU
             +--------------------+
             |                    |
    /reset-->*                    *-->halt
             |                    |
             |  +--------------+  *-->error
             |  | math.divider |  |
             |  +--------------+  *-->ticks[64]
             |                    |
             |  +--------------+  |
             |  | math.shifter |  |
             |  +--------------+  *--> R0[64]
             |                    |
    R1[64]-->*  +--------------+  *--> R1[64]
             |  |   prgm.mem   |  |
    R2[64]-->*  |    64 bit    |  *--> R2[64]
             |  +--------------+  |
    R3[64]-->*                    *--> R3[64]
             |  +--------------+  |
    R4[64]-->*  |   data.mem   |  *--> R4[64]
             |  |    8 bit     |  |
    R5[64]-->*  +--------------+  *--> R5[64]
             |                    |
             |  +--------------+  *--> R6[64]
             |  | call.handler |  |
             |  +--------------+  *--> R7[64]
             |                    |
             |                    *--> R8[64]
             |                    |
             |                    *--> R9[64]
             |                    |
             +--------------------+
@enduml